---
- name: Add Telegraf repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add Telegraf apt repo
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian jessie stable"
    state: present

- name: Install Telegraf
  apt:
    name: telegraf
    update_cache: yes
    state: present

- name: Configure telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes

- name: Add telegraph to vtysh sudo users
  lineinfile:
    dest: "/etc/sudoers"
    regexp: '^telegraf'
    line: 'telegraf ALL=(root) NOPASSWD: /usr/bin/vtysh,/usr/bin/fping'
    validate: 'visudo -cf %s'

- name: add telegraf to adm group so that it can run lldpctl without errors
  user:  name=telegraf append=yes groups=adm
